[WiP] Infrastructure Manager creates secrets when a new Cluster Inventory CR is created.
kyma-project/infrastructure-manager pull request #37
Opened 2023-09-15 14:52 UTC by Disper

**Description**

Changes proposed in this pull request:

- Adds test for secret creation
- ...
- ...

/area control-plane
/kind feature

**Related issue(s)**
#10

2023-09-21 07:35 UTC, VOID404 reviewed
Other than that, it seems fine

2023-09-21 08:50 UTC, Disper commented on Dockerfile
> +COPY . ./
improved in ab86a67e87ab2e23649fd02d438893674d9d2c91

2023-09-22 04:38 UTC, akgalwas commented on internal/controller/gardener_cluster_controller.go
> +	labels["operator.kyma-project.io/managed-by"] = "lifecycle-manager"
I think think it should be "infrastructure-manager" instead of "lifecycle-manager"

2023-09-22 04:38 UTC, akgalwas commented on internal/controller/gardener_cluster_controller.go
> +		return r.ResultWithoutRequeue(), err
I think if we failed to read Gardener Cluster resource we should requeue the event.

2023-09-22 04:38 UTC, akgalwas commented on internal/controller/gardener_cluster_controller.go
> +			return r.ResultWithoutRequeue(), err
The same here. If we cannot read the secret, and the error differs from `IsNotFound` we should requeue.

2023-09-22 04:58 UTC, akgalwas requested changes
The PR looks good, but let's fix the requeuing issues.

2023-09-22 06:21 UTC, akgalwas approved these changes

2023-09-22 06:24 UTC, akgalwas submitted a review, later dismissed

2023-09-22 06:31 UTC, akgalwas approved these changes

2023-09-22 06:31 UTC, merged