oidc extension added only if controlled-by-provisioner value is disabled
kyma-project/infrastructure-manager pull request #373
Opened 2024-09-10 10:03 UTC by Disper

**Description**
> The Provisioner is enabling it only for new runtimes. In KIM, it looks like we enable it always - also for updates.
> Would KIM be able to detect if the RUntime was already created, or does it not know whether a Runtime is new or already exists?

Changes proposed in this pull request:

- extension applied only if `"kyma-project.io/controlled-by-provisioner": "false"`
- ...
- ...

**Related issue(s)**

2024-09-10 10:07 UTC, Disper commented
After creating this PR I understand that this idea does not really make much sense. Existing clusters will anyway not have the OIDC extension enabled by KIM until we migrate the cluster:
1. We create Runtime CR for the cluster
2. Shoot will anyway then have `"kyma-project.io/controlled-by-provisioner": "false"` label

2024-09-11 07:12 UTC, Disper commented
Implementation adjusted to rely on `operator.kyma-project.io/created-by-migrator` label instead.

2024-09-13 13:05 UTC, akgalwas commented on internal/gardener/shoot/extender/oidc.go
> +	createdByMigrator := shoot.Labels["operator.kyma-project.io/created-by-migrator"]
`operator.kyma-project.io/created-by-migrator` is not available on the shoot.

2024-09-13 13:10 UTC, akgalwas requested changes
This will not work. The implementation looks for `operator.kyma-project.io/created-by-migrator` label on the shoot. The migrator app sets it on a **_runtime_**. There are two solutions:
- We can just check runtime for the label
- We can modify KIM to set this label on a shoot.

I think option number one is the best, as we don't need to mark shoot as migrated since Runtime CR contains this information already.

2024-09-16 08:24 UTC, akgalwas approved these changes

2024-09-16 08:29 UTC, merged