WiP zones are always retrieved from the existing shoot if it exists
kyma-project/infrastructure-manager pull request #460
Opened 2024-10-29 06:15 UTC by Disper

**Description**

Changes proposed in this pull request:

- zones are always retrieved from the existing shoot if it exists
- ...
- ...

**Related issue(s)**

2024-10-31 07:31 UTC, akgalwas requested changes
In general the solution is OK, however, I believe we need to align the PR with ongoing Audit Log work. The way of enhancing converter with the context information should be discussed.

2024-10-31 07:31 UTC, akgalwas commented on pkg/gardener/shoot/extender/dns.go
> +		secretReference := gardener.NamedResourceReference{
I checked the validating webhook's [code](https://github.com/gardener/gardener-extension-shoot-dns-service/blob/master/pkg/admission/validator/shoot_validator.go#L57) once more. Now I'm sure we do the correct thing. Once the extension contains the secret reference the spec.resources field needs to be set accordingly.

2024-10-31 07:31 UTC, akgalwas commented on pkg/gardener/shoot/converter.go
> +func NewConverter(config config.ConverterConfig, shootFromState *gardener.Shoot) Converter {
I'm not convinced to directly pass shoot to the converter. I would introduce some kind of "dynamic configuration". We need to align it with [Audit log PR](https://github.com/kyma-project/infrastructure-manager/pull/472) to have one concistent solution and make rebasing easier.

2024-11-05 06:35 UTC, Disper commented
Closing in favor of #476 and  https://github.com/m00g3n/cluster-inventory/pull/6

2024-11-05 06:35 UTC, closed without merging