improves gardener errors handling for those which can be retried
kyma-project/infrastructure-manager pull request #480
Opened 2024-11-07 06:49 UTC by Disper

**Description**

Changes proposed in this pull request:

- improves error handling for errors that could be retried 
- in  clusterrolebinding state is now requeued when listing or update fails instead of stopping 

**Related issue(s)**

2024-11-07 08:20 UTC, Disper commented on pkg/gardener/gardener_error_handler.go
> +func CombineErrorDescriptions(lastErrors []gardener.LastError) string {
not yet used as I've created it without knowing that the ToErrReason existed in a different place. Kept it as it combined more human readable description

2024-11-08 06:11 UTC, Disper commented
There is a related issue https://github.com/kyma-project/infrastructure-manager/issues/369

2024-11-09 10:15 UTC, koala7659 approved these changes
LGTM

2024-11-09 10:15 UTC, koala7659 commented on internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
> +		if imgardenerhandler.IsRetryable(lastErrors) {
General comment: It is strange that inside this method the code `ErrorInfraRateLimitsExceeded` we treated as Retryable is also considered as NON Retryable. But we must assume we did not use this code properly. This code was basically copy & pasted from old Provisioer

2024-11-09 11:10 UTC, koala7659 requested changes
Please see my comments

2024-11-09 11:10 UTC, koala7659 commented on internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
> +			// TODO: should update status?
We can update status with 

```
		s.instance.UpdateStatePending(
			imv1.ConditionTypeRuntimeProvisioned,
			imv1.ConditionReasonShootCreationPending,
			"Unknown",
			"Retryable gardener errors during cluster reconcile")
```

2024-11-09 11:10 UTC, koala7659 commented on internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
> +			//TODO: should update status?
We can update status with 

```
		s.instance.UpdateStatePending(
			imv1.ConditionTypeRuntimeProvisioned,
			imv1.ConditionReasonShootCreationPending,
			"Unknown",
			"Retryable gardener errors during cluster provisioning")
```

2024-11-18 08:01 UTC, koala7659 approved these changes
LGTM

2024-11-18 08:01 UTC, merged